# Archivo: .github/workflows/02-workflow-events.yaml
name: "02 - Eventos"

on:
  pull_request:           # Se activa en la creación o actualización de un pull request
  workflow_dispatch:      # Desencadenante manual desde GitHub Actions
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: echo "Este workflow fue activado por el evento:" ${{ github.event_name }}