# Archivo: .github/workflows/02-workflow-events.yaml
name: "02 - Eventos"

on:
  push:  # Trigger inicial

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: echo ${{ github.event_name }}"