# Archivo: .github/workflows/02-workflow-events.yaml
name: "02 - Eventos"

on:
  push:  # Trigger inicial
  pull_request:           # Se activa en la creación o actualización de un pull request
  schedule:               # Programación automática
    - cron: '0 0 * * *'   # Ejecución diaria a medianoche UTC
  workflow_dispatch:      # Desencadenante manual desde GitHub Actions
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: echo "Este workflow fue activado por el evento:" ${{ github.event_name }}